#Consider all integer combinations of a^b for 2<= a <= 5 and 2 <= b <= 5. 
#There are 15 distinct terms
#How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100

def distinct_terms():
    list = []
    for a in range(2, 101):
        for b in range(2, 101):
            term = a**b
            list.append(term)
    return len(set(list))

def distinct_terms_2():
    terms = (a**b for a in range(2, 101) for b in range(2, 101))
    return len(set(terms))

